### ISSUE TITLE
Check for and resolve possible regressions in CNXML export after Slate update

### ISSUE THREAD

**Issue by aiwenar** [openstax-poland/cnx-designer#130]
Check for and resolve possible regressions in CNXML export after Slate update

**Comment by aiwenar** [comment]
All modules pass RelaxNG validation.



## Changes which are not issues

- Namespaces `http://katalysteducation.org/cmlnle/1.0`, `http://katalysteducation.org/cxlxt/1.0`, and `http://adaptarr.naukosfera.com/editing/1.0` are now included in every module, even when not in use.

- Attributes `id` and `module-id` of `<document>` are now set to module's ID, whereas previously they were set to `new`. Unlike with element IDs the fact that this is an UUID does not seem to be a problem, as all modules passed RelaxNG validation. These attributes, while required, are not used by Adaptarr or legacy, so this change shouldn't affect anything.

- All inline elements now have ID set.

- Order of properties on some elements have changed.

- `<list>` elements with `list-type="bulleted"` now omit this property (this is not an issue as `bulleted` is the default value).

- Order of classes in `class=` changed. This should not be an issue for webview, Rex, and the new PDF pipeline, but might be an issue for the old pipeline.

- XML is now formatted and block elements indented, but formatting of text and inline elements has not changed.

- Sequences of multiple white spaces in text and attributes are collapsed to a single space. This is acceptable, as in all but some extreme cases this won't affect how the text is being displayed.

- White space from beginning and end of block text elements and attributes was removed.

- White space at beginning and end of inline elements was moved outside of them.

- Empty inline elements (such as an `<emphasis>` containing just white space) have been removed.

- `<equation>` elements containing `<math display="block">` elements which were previously inside paragraphs were moved outside of them.



## Possible issues

- Figures which previously were inside admonitions (`<note>` elements) and exercises have been moved outside of them. 

    - a09a7772-006d-4a5f-8c64-fbd4bfd82607
    - 76d8ab39-1b38-4da6-9295-57c5693b62cd
    - e228dcbb-0b19-49f0-9b75-8ec432443cfb
    - 76f34b6b-2563-4657-aff7-16c9df8c58cc
    - 91ea0436-6e44-4c76-abbf-7a43bd4f09e4
    - 29b6c262-ae0a-4b39-baf4-009e0e06aafb - here this resulted in a `<note>` being split in two
    - 42b51d65-4f74-42b7-9b70-6409503be74f
    - a1d3e845-daa4-4bca-a5d6-79f0a550677c - here this resulted in a `<note>` begin split in two
    - fc492bb9-fef1-4c17-a792-7bffbbf176a5 - here this resulted in a `<note>` begin split in two
    - e041bcca-22e9-4233-b0f5-8a51d3673b26
    - 5457d0a7-c6a2-418d-adb2-2dfecf04d6d7 - here this resulted in a `<note>` begin split in two
    - e3aaef38-6149-4e4f-a1cf-bc39f886ccda - here this resulted in a `<note>` begin split in two
    - b2ce78de-a049-4c85-a40e-5c6e0954379a - here this resulted in a `<note>` begin split in two
    - 6c64d20f-57ad-4c02-8b77-c899c2f279ff



## Issues

- [ ] openstax-poland/adaptarr-front#562 Modules now have `xml:lang` set to `en`. This is incorrect, as out modules are in Polish (and are configured as such in Adaptarr, both on production and staging). `xml:lang` was previously unset.

- [ ] openstax-poland/adaptarr-backlog#75 Media type of some images changed from png to jpeg

- [ ] openstax-poland/cnx-designer#131 Underline is removed when loading Stres a choroby (5457d0a7-c6a2-418d-adb2-2dfecf04d6d7)
